quiet: true
soft_fail: true

# skip-check:
  # - CKV2_AWS_5   # Ensure that security groups are attached to resources (not left unattached)
  # - CKV2_AWS_57  # Ensure Secrets Manager secrets should have automatic rotation enabled
  # - CKV2_AWS_61  # Ensure that an S3 bucket has a lifecycle configuration
  # - CKV2_AWS_62  # Ensure S3 buckets should have event notifications enabled

  # - CKV2_GHA_1   # Ensure top-level permissions are not set to write-all

  # - CKV_AWS_5    # Ensure all data stored in the Elasticsearch is securely encrypted at rest
  # - CKV_AWS_18   # Ensure S3 bucket has access logging enabled
  # - CKV_AWS_21   # Ensure all data stored in the S3 bucket have versioning enabled

  # - CKV_AWS_61   # Ensure AWS IAM policy does not allow assume role permission across all services
  # - CKV_AWS_62   # Ensure IAM policies that allow full “-” administrative privileges are not created

  # - CKV_AWS_111  # Ensure IAM policies does not allow write access without constraints
  # - CKV_AWS_144  # Ensure that S3 bucket has cross-region replication enabled
  # - CKV_AWS_145  # Ensure that S3 buckets are encrypted with KMS by default
  # - CKV_AWS_158  # Ensure that CloudWatch Log Group is encrypted by KMS

  # - CKV_AWS_296  # Ensure DMS endpoint uses Customer Managed Key (CMK)
  # - CKV_AWS_298  # Ensure DMS S3 uses Customer Managed Key (CMK)
  # - CKV_AWS_356  # Ensure no IAM policies documents allow “*” as a statement’s resource for restrictable actions
  # - CKV_AWS_382  # Ensure no security groups allow egress from 0.0.0.0:0 to port -1

  # - CKV_TF_1     # Ensure Terraform module sources use a commit hash
  # - CKV_TF_2     # Ensure Terraform module sources use a tag with a version number
  # - CKV_TF_5     # Ensure all Terraform modules specify an exact version constraint
