---
name: Dependency Review

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  dependency-review:
    name: Dependency Review
    permissions:
      contents: read
    uses:
      ministryofjustice/data-engineering-github-actions/.github/workflows/reusable-dependency-review.yml@867b0f83016b15386c659b6a18fbd85037eb662f  # v1.0.0
